import datetime
now = datetime.datetime.now()
print ("Current date and time :",now.strftime("%Y-%m-%d %H:%M:%S"))
year = now.strftime("%Y")
print ("Current year :",year)
month = now.strftime("%m")
print ("Current month :",month)
week = now.strftime("%W")
print ("Current week number :",week)
day=  now.strftime('%A')
print("Current day :",day)
yearday=now.strftime("%j")
print("Current day of year :",yearday)
monthday=now.strftime("%d")
print("Current day of month :",monthday)
weekday=now.strftime("%w")
print("Current day of week :",weekday)
